import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ContestActions } from "@/components/ContestActions";
import { ContestLocationMap } from "@/components/ContestLocationMap";
import { Footer, Header } from "@/components/Header";
import { getContestPageData, type ContestDocument, type ContestEvidence } from "@/lib/contest-page";

const siteUrl = "https://simulaai-kappa.vercel.app";
const date = (value: string | null) => value ? new Intl.DateTimeFormat("pt-BR", { timeZone: "UTC" }).format(new Date(`${value.slice(0, 10)}T12:00:00Z`)) : "Não informada";
const dateTime = (value: string) => new Intl.DateTimeFormat("pt-BR", { dateStyle: "medium", timeStyle: "short", timeZone: "America/Sao_Paulo" }).format(new Date(value));
const money = (value: number | null) => value == null ? "Não informado" : value.toLocaleString("pt-BR", { style: "currency", currency: "BRL" });
const text = (value: string | number | null) => value == null || value === "" ? "Não informado" : String(value);

function officialEvidence(evidence: ContestEvidence[], ...fields: string[]) { return evidence.some((item) => item.source_tier === 1 && fields.includes(item.field_name)); }
function Fact({ label, value, confirmed }: { label: string; value: string; confirmed: boolean }) { return <div className="rounded-2xl border border-zinc-200 p-4"><dt className="text-xs font-bold uppercase tracking-wide text-zinc-500">{label}</dt><dd className="mt-1 font-semibold text-zinc-950">{confirmed ? value : "Não confirmado"}</dd></div>; }
function DocumentList({ items, empty }: { items: ContestDocument[]; empty: string }) { return items.length ? <div className="mt-4 space-y-3">{items.map((document, index) => <a key={`${document.source_url}-${index}`} href={document.source_url} target="_blank" rel="noopener noreferrer" className="block rounded-2xl border border-zinc-200 p-4 transition hover:border-violet-400"><span className="font-bold text-zinc-950">{document.document_type || document.relationship_type}</span><span className="mt-1 block text-sm text-zinc-500">{document.source_name || "Fonte oficial"} · {date(document.published_at || document.observed_at)}</span></a>)}</div> : <p className="mt-4 text-sm text-zinc-500">{empty}</p>; }

export async function generateMetadata({ params }: { params: Promise<{ id: string }> }): Promise<Metadata> {
  const { id } = await params; const contest = await getContestPageData(id);
  if (!contest) return { title: "Concurso não encontrado — SimulaAí" };
  const description = `${contest.orgao}: ${contest.titulo}. Banca ${contest.banca || "não informada"}, ${contest.vagas == null ? "vagas não informadas" : `${contest.vagas} vagas`}. Consulte edital, datas e evidências.`;
  const canonical = `${siteUrl}/concursos/${contest.id}`;
  return { title: `${contest.titulo} — ${contest.orgao} | SimulaAí`, description, alternates: { canonical }, openGraph: { title: contest.titulo, description, type: "article", url: canonical }, twitter: { card: "summary", title: contest.titulo, description } };
}

export default async function ContestPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const contest = await getContestPageData(id); if (!contest) notFound();
  const forecast = contest.status?.toUpperCase().includes("PREVIST") ?? false;
  const official = (field: string, ...aliases: string[]) => officialEvidence(contest.evidence, field, ...aliases);
  const locationConfirmed = official("scope", "state_code", "city", "location_label");
  const retifications = contest.documents.filter((document) => document.relationship_type === "RETIFICATION");
  const documents = contest.documents.filter((document) => document.relationship_type !== "RETIFICATION");
  const sources = contest.evidence.filter((item, index, all) => all.findIndex((candidate) => candidate.source_url === item.source_url && candidate.field_name === item.field_name) === index).slice(0, 20);
  const jsonLd: Record<string, unknown> = { "@context": "https://schema.org", "@type": "JobPosting", title: contest.titulo, description: `Concurso público de ${contest.orgao}. Consulte dados confirmados, edital e fontes.`, identifier: { "@type": "PropertyValue", name: contest.orgao, value: contest.edital_number || contest.id }, hiringOrganization: { "@type": "Organization", name: contest.orgao }, datePosted: contest.updated_at, directApply: false, url: `${siteUrl}/concursos/${contest.id}` };
  if (contest.inscricao_fim && official("inscricao_fim")) jsonLd.validThrough = `${contest.inscricao_fim}T23:59:59-03:00`;
  if (contest.salario != null && official("salario")) jsonLd.baseSalary = { "@type": "MonetaryAmount", currency: "BRL", value: { "@type": "QuantitativeValue", value: contest.salario, unitText: "MONTH" } };
  if (contest.city && contest.state_code && locationConfirmed) jsonLd.jobLocation = { "@type": "Place", address: { "@type": "PostalAddress", addressLocality: contest.city, addressRegion: contest.state_code, addressCountry: "BR" } };

  return <div className="mesh min-h-screen"><Header /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd).replace(/</g, "\\u003c") }} /><main className="mx-auto max-w-6xl px-6 py-8">
    <Link href="/concursos" className="text-sm font-bold text-cyan-300">← Voltar para busca</Link>
    <section className="mt-5 glass rounded-[32px] p-7 md:p-10"><div className="flex flex-wrap items-start justify-between gap-5"><div className="max-w-3xl"><p className="text-sm font-bold uppercase tracking-widest text-cyan-300">{contest.orgao}</p><h1 className="mt-2 font-display text-3xl font-bold md:text-5xl">{contest.titulo}</h1><p className="mt-3 text-white/60">Banca {contest.banca || "não informada"} · atualizado em {dateTime(contest.updated_at)}</p></div><span className={`rounded-full px-4 py-2 text-sm font-black ${forecast ? "bg-amber-300 text-zinc-950" : contest.quality_status === "VERIFIED" ? "bg-emerald-300 text-zinc-950" : "bg-white/10"}`}>{forecast ? "PREVISTO" : contest.quality_status === "VERIFIED" ? "CONFIRMADO" : "EM VERIFICAÇÃO"}</span></div><div className="mt-7"><ContestActions contestId={contest.id} simuladoSlug={contest.simulado_slug} /></div></section>

    <div className="mt-7 grid gap-7 lg:grid-cols-[1.3fr_.7fr]"><div className="space-y-7">
      <section className="rounded-[28px] bg-white p-6 text-zinc-950"><div className="flex items-center gap-3"><span className="rounded-full bg-emerald-100 px-3 py-1 text-xs font-black text-emerald-800">CONFIRMADO</span><h2 className="text-2xl font-bold">Informações com evidência oficial</h2></div><p className="mt-2 text-sm text-zinc-500">Campos sem fonte oficial vinculada aparecem como “Não confirmado”, sem serem tratados como previsão.</p><dl className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><Fact label="Órgão" value={contest.orgao} confirmed={official("orgao")} /><Fact label="Banca" value={text(contest.banca)} confirmed={official("banca")} /><Fact label="Status" value={text(contest.status)} confirmed={!forecast && official("status")} /><Fact label="Vagas" value={text(contest.vagas)} confirmed={official("vagas")} /><Fact label="Salário" value={money(contest.salario)} confirmed={official("salario")} /><Fact label="Níveis" value={contest.escolaridade.join(", ") || "Não informados"} confirmed={official("escolaridade")} /><Fact label="Cargos" value={contest.cargos.join(", ") || "Não informados"} confirmed={official("cargos")} /><Fact label="Inscrições" value={`${date(contest.inscricao_inicio)} a ${date(contest.inscricao_fim)}`} confirmed={official("inscricao_inicio") && official("inscricao_fim")} /><Fact label="Prova" value={date(contest.prova_data)} confirmed={official("prova_data")} /></dl></section>
      <section className="rounded-[28px] border border-amber-300/30 bg-amber-300/10 p-6"><div className="flex items-center gap-3"><span className="rounded-full bg-amber-300 px-3 py-1 text-xs font-black text-zinc-950">PREVISTO</span><h2 className="text-2xl font-bold">Informações previstas</h2></div>{forecast ? <p className="mt-4">O órgão classifica este concurso como <strong>{contest.status}</strong>. Isso não é misturado aos fatos confirmados acima; datas e números continuam dependentes de evidência oficial própria.</p> : <p className="mt-4 text-white/70">Nenhuma previsão é apresentada como fato confirmado nesta página.</p>}</section>
      <section className="rounded-[28px] bg-white p-6 text-zinc-950"><h2 className="text-2xl font-bold">Edital e documentos</h2>{contest.edital_url && <a href={contest.edital_url} target="_blank" rel="noopener noreferrer" className="mt-4 inline-block rounded-full bg-zinc-950 px-5 py-3 font-bold text-white">Abrir edital oficial ↗</a>}<DocumentList items={documents} empty="Nenhum documento adicional publicado." /><h3 className="mt-7 text-xl font-bold">Retificações</h3><DocumentList items={retifications} empty="Nenhuma retificação vinculada a este concurso." /></section>
      <section className="rounded-[28px] bg-white p-6 text-zinc-950"><h2 className="text-2xl font-bold">Fontes e evidências</h2><p className="mt-1 text-sm text-zinc-500">Trechos e links que sustentam os campos confirmados.</p>{sources.length ? <div className="mt-5 space-y-3">{sources.map((item, index) => <article key={`${item.field_name}-${item.source_url}-${index}`} className="rounded-2xl bg-zinc-50 p-4"><div className="flex flex-wrap justify-between gap-2"><b>{item.field_name}</b><span className="text-xs text-zinc-500">Fonte nível {item.source_tier} · confiança {Math.round(Number(item.confidence) * 100)}%</span></div><p className="mt-2 text-sm text-zinc-700">{item.evidence_text}</p><a href={item.source_url} target="_blank" rel="noopener noreferrer" className="mt-2 inline-block text-sm font-bold text-violet-700">Ver fonte ↗</a></article>)}</div> : <p className="mt-4 text-zinc-500">Nenhuma evidência pública vinculada.</p>}</section>
    </div><aside className="space-y-7"><section className="glass rounded-[28px] p-6"><h2 className="text-xl font-bold">Localidade</h2><p className="mt-2 text-white/70">{locationConfirmed ? contest.location_label || [contest.city, contest.state_code, contest.scope].filter(Boolean).join(" · ") : "Localidade não confirmada"}</p></section>{contest.latitude != null && contest.longitude != null && locationConfirmed && <ContestLocationMap latitude={contest.latitude} longitude={contest.longitude} label={contest.location_label || contest.titulo} />}<section className="glass rounded-[28px] p-6"><h2 className="text-xl font-bold">Transparência</h2><dl className="mt-4 space-y-3 text-sm"><div><dt className="text-white/50">Última atualização</dt><dd>{dateTime(contest.updated_at)}</dd></div><div><dt className="text-white/50">Qualidade</dt><dd>{contest.quality_status}</dd></div><div><dt className="text-white/50">Fonte oficial</dt><dd>{contest.official_source || "Não informada"}</dd></div><div><dt className="text-white/50">Edital</dt><dd>{contest.edital_number || "Não informado"}</dd></div></dl></section></aside></div>
  </main><Footer /></div>;
}
