import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { createCollectorDatabase } from "./support/collectorDatabase";
import { mayActivateCandidate } from "../src/lib/collector/sourceRegistry";
import { adapters } from "../src/lib/collector/adapters";

async function main() {
  const { db } = await createCollectorDatabase();
  try {
    const before = await db.query<{ count: number }>("select count(*)::int count from collector_documents");
    await db.exec(readFileSync("../supabase/migrations/20261004203913_admin_operations.sql", "utf8"));
    await db.exec(readFileSync("../supabase/migrations/20261005120000_restrict_admin_document_retry.sql", "utf8"));
    await db.exec(readFileSync("../supabase/migrations/20261006010000_operational_source_approval.sql", "utf8"));
    const after = await db.query<{ count: number }>("select count(*)::int count from collector_documents");
    assert.equal(after.rows[0].count, before.rows[0].count, "migration may not modify existing documents");
    assert.equal((await db.query<{ count: number }>("select count(*)::int count from ops_admin_members")).rows[0].count, 0, "no implicit admin");
    const roles = await db.query<{ anon: boolean; authenticated: boolean; service: boolean; rls: boolean }>("select has_function_privilege('anon','ops_apply_action(uuid,text,uuid,text,text)','execute') anon, has_function_privilege('authenticated','ops_apply_action(uuid,text,uuid,text,text)','execute') authenticated, has_function_privilege('service_role','ops_apply_action(uuid,text,uuid,text,text)','execute') service, (select relrowsecurity from pg_class where oid='ops_admin_members'::regclass) rls");
    assert.deepEqual(roles.rows[0], { anon: false, authenticated: false, service: true, rls: true });
    const approvalRoles = await db.query<{ anon: boolean; authenticated: boolean; service: boolean }>("select has_function_privilege('anon','ops_approve_source(uuid,uuid,text,text,boolean)','execute') anon, has_function_privilege('authenticated','ops_approve_source(uuid,uuid,text,text,boolean)','execute') authenticated, has_function_privilege('service_role','ops_approve_source(uuid,uuid,text,text,boolean)','execute') service");
    assert.deepEqual(approvalRoles.rows[0], { anon: false, authenticated: false, service: true });
    for (const adapter of adapters) {
      const compiled = (await db.query<{ name: string; base_url: string; adapter: string; tier: number }>("select name,base_url,adapter,tier from ops_known_source_adapter($1)", [new URL(adapter.baseUrl).hostname])).rows[0];
      assert.deepEqual(compiled, { name: adapter.sourceName, base_url: adapter.baseUrl, adapter: adapter.sourceName, tier: adapter.tier }, "SQL activation catalog must match compiled adapters");
    }
    const actor = (await db.query<{ id: string }>("insert into auth.users(email) values('operator@fixture.test') returning id")).rows[0].id;
    const outsider = (await db.query<{ id: string }>("insert into auth.users(email) values('outsider@fixture.test') returning id")).rows[0].id;
    const source = (await db.query<{ id: string }>("select id from collector_sources limit 1")).rows[0].id;
    const doc = (await db.query<{ id: string }>("insert into collector_documents(source_id,canonical_url,source_url,title,content_hash,status,raw_text,ai_last_error_code) values($1,'https://official.test/retry','https://official.test/retry','Retry','ops-retry','FAILED','document body','TIMEOUT') returning id", [source])).rows[0].id;
    const permanent = (await db.query<{ id: string }>("insert into collector_documents(source_id,canonical_url,source_url,title,content_hash,status,raw_text,ai_last_error_code,metadata) values($1,'https://official.test/permanent','https://official.test/permanent','Contacts','ops-permanent','FAILED','document body','MAX_RETRIES','{\"sync_error\":\"INSUFFICIENT_IDENTITY\"}') returning id", [source])).rows[0].id;
    await assert.rejects(db.query("select ops_apply_action($1,'RETRY_DOCUMENT',$2)", [outsider, doc]), /OPS_FORBIDDEN/);
    assert.equal((await db.query<{ status: string }>("select status from collector_documents where id=$1", [doc])).rows[0].status, "FAILED");
    await db.query("insert into ops_admin_members(user_id) values($1)", [actor]);
    await assert.rejects(db.query("select ops_apply_action($1,'RETRY_DOCUMENT',$2)", [actor, permanent]), /OPS_TARGET_NOT_ACTIONABLE/);
    assert.equal((await db.query<{ status: string }>("select status from collector_documents where id=$1", [permanent])).rows[0].status, "FAILED");
    await db.query("select ops_apply_action($1,'RETRY_DOCUMENT',$2)", [actor, doc]);
    assert.equal((await db.query<{ status: string; ai_retry_count: number }>("select status,ai_retry_count from collector_documents where id=$1", [doc])).rows[0].status, "AI_PENDING");
    await assert.rejects(db.query("select ops_apply_action($1,'RETRY_DOCUMENT',$2)", [actor, doc]), /OPS_TARGET_NOT_ACTIONABLE/);
    const candidate = (await db.query<{ id: string }>("insert into source_candidates(url,domain) values('https://official.test/contest','official.test') returning id")).rows[0].id;
    await assert.rejects(db.query("select ops_apply_action($1,'APPROVE_SOURCE',$2,'Checked official source','http://official.test')", [actor, candidate]), /OPS_INVALID_OFFICIAL_URL/);
    await db.query("select ops_apply_action($1,'APPROVE_SOURCE',$2,'Verified official contest page','https://official.test/contest')", [actor, candidate]);
    const approved = (await db.query<{ status: string; official_url: string; reviewed_by: string; reviewed_at: string }>("select status,official_url,reviewed_by,reviewed_at from source_candidates where id=$1", [candidate])).rows[0];
    assert.equal(approved.status, "APPROVED");
    assert.equal(approved.official_url, "https://official.test/contest");
    assert.equal(approved.reviewed_by, actor);
    assert.ok(approved.reviewed_at);
    assert.equal(mayActivateCandidate({ status: approved.status, officialUrl: approved.official_url, reviewedBy: approved.reviewed_by }), true);
    const registered = (await db.query<{ id: string; enabled: boolean; adapter: string | null; tier: number; source_type: string; disabled_reason: string; approved_candidate_id: string }>("select id,enabled,adapter,tier,source_type,disabled_reason,approved_candidate_id from collector_sources where hostname='official.test'")).rows[0];
    assert.ok(registered.id, "approval RPC itself must create the operational source");
    assert.equal(registered.enabled, false); assert.equal(registered.adapter, null); assert.equal(registered.tier, 3);
    assert.equal(registered.source_type, "DISCOVERY_AUXILIAR"); assert.equal(registered.disabled_reason, "APPROVED_PENDING_ADAPTER");
    assert.equal(registered.approved_candidate_id, candidate);
    assert.equal((await db.query<{ operational_source_id: string }>("select operational_source_id from source_candidates where id=$1", [candidate])).rows[0].operational_source_id, registered.id);
    const rejected = (await db.query<{ id: string }>("insert into source_candidates(url,domain) values('https://aggregator.test/logo.png','aggregator.test') returning id")).rows[0].id;
    await db.query("select ops_apply_action($1,'REJECT_SOURCE_CANDIDATE',$2,'Image is not a source')", [actor, rejected]);
    assert.equal((await db.query<{ status: string }>("select status from source_candidates where id=$1", [rejected])).rows[0].status, "REJECTED");
    await assert.rejects(db.query("insert into collector_sources(name,base_url,type,tier,source_type,adapter,approved_candidate_id) values('Rejected ops fixture','https://rejected.test','portal',3,'DISCOVERY_AUXILIAR','Rejected ops fixture',$1)", [rejected]), /SOURCE_APPROVAL_REQUIRED/);
    const contest = (await db.query<{ id: string }>("insert into concursos(orgao,titulo,status,quality_status,is_publishable) values('Órgão','Conflito','previsto','CONFLICTED',false) returning id")).rows[0].id;
    await db.query("select ops_apply_action($1,'REVIEW_CONFLICT',$2,'Aguardando edital para resolver')", [actor, contest]);
    assert.equal((await db.query<{ quality_status: string }>("select quality_status from concursos where id=$1", [contest])).rows[0].quality_status, "CONFLICTED", "review must not rewrite factual quality");
    assert.equal((await db.query<{ count: number }>("select count(*)::int count from ops_conflict_reviews where concurso_id=$1", [contest])).rows[0].count, 1);
    assert.equal((await db.query<{ count: number }>("select count(*)::int count from ops_action_log", [])).rows[0].count, 4, "only successful actions are audited");
    assert.deepEqual((await db.query<{ actor_user_id: string; action: string; target_id: string; official_url: string }>("select actor_user_id,action,target_id,details->>'official_url' official_url from ops_action_log where action='APPROVE_SOURCE'")).rows[0], { actor_user_id: actor, action: "APPROVE_SOURCE", target_id: candidate, official_url: "https://official.test/contest" }, "source approval must retain actor and official evidence in audit");
    await assert.rejects(db.query("select ops_apply_action($1,'ARBITRARY_SQL',$2)", [actor, contest]), /OPS_UNKNOWN_ACTION/);
    await assert.rejects(db.query("select ops_approve_source($1,$2,'Activate rejected source','https://aggregator.test/logo.png',true)", [actor, rejected]), /OPS_TARGET_NOT_ACTIONABLE/);
    await assert.rejects(db.query("select ops_approve_source($1,$2,'Activate unknown source','https://official.test/contest',true)", [actor, candidate]), /OPS_ADAPTER_NOT_SUPPORTED/);
    await db.query("select ops_apply_action($1,'APPROVE_SOURCE',$2,'Repeat verified registration','https://official.test/contest')", [actor, candidate]);
    assert.equal((await db.query<{ count: number }>("select count(*)::int count from collector_sources where hostname='official.test'")).rows[0].count, 1);
    const secondCandidate = (await db.query<{ id: string }>("insert into source_candidates(url,domain) values('https://official.test/second','official.test') returning id")).rows[0].id;
    await db.query("select ops_apply_action($1,'APPROVE_SOURCE',$2,'Second page on same source','https://official.test/second')", [actor, secondCandidate]);
    assert.equal((await db.query<{ operational_source_id: string }>("select operational_source_id from source_candidates where id=$1", [secondCandidate])).rows[0].operational_source_id, registered.id);
    assert.equal((await db.query<{ operational_source_id: string }>("select operational_source_id from source_candidates where id=$1", [candidate])).rows[0].operational_source_id, registered.id, "later approval must not lose prior history linkage");

    const fgvCandidate = (await db.query<{ id: string }>("insert into source_candidates(url,domain) values('https://conhecimento.fgv.br/concursos/fixture','conhecimento.fgv.br') returning id")).rows[0].id;
    await db.query("update collector_sources set enabled=false,disabled_reason='Fixture controlled disable',disabled_by=$1,disabled_at=now(),failure_count=4,last_status='FAILED' where name='FGV'", [actor]);
    await db.query("select ops_apply_action($1,'APPROVE_SOURCE',$2,'Reviewed FGV contest page','https://conhecimento.fgv.br/concursos/fixture')", [actor, fgvCandidate]);
    assert.equal((await db.query<{ enabled: boolean }>("select enabled from collector_sources where name='FGV'")).rows[0].enabled, false, "approval defaults to no activation");
    const initialReview = (await db.query<{ reviewed_at: string; review_notes: string }>("select reviewed_at,review_notes from source_candidates where id=$1", [fgvCandidate])).rows[0];
    await db.query("select ops_approve_source($1,$2,'Explicit known adapter activation','https://conhecimento.fgv.br/concursos/fixture',true)", [actor, fgvCandidate]);
    assert.deepEqual((await db.query<{ enabled: boolean; failure_count: number; health_status: string; disabled_reason: string | null }>("select enabled,failure_count,health_status,disabled_reason from collector_sources where name='FGV'")).rows[0], { enabled: true, failure_count: 4, health_status: "DEGRADED", disabled_reason: null }, "activation preserves failure history");
    assert.deepEqual((await db.query<{ reviewed_at: string; review_notes: string }>("select reviewed_at,review_notes from source_candidates where id=$1", [fgvCandidate])).rows[0], initialReview, "activation preserves original review");
    const activeBefore = (await db.query("select name,base_url,adapter,tier,source_type,enabled,failure_count,health_status,last_status from collector_sources where name='FGV'")).rows[0];
    await db.query("select ops_apply_action($1,'APPROVE_SOURCE',$2,'Repeat approval preserves active source','https://conhecimento.fgv.br/concursos/fixture')", [actor, fgvCandidate]);
    assert.deepEqual((await db.query("select name,base_url,adapter,tier,source_type,enabled,failure_count,health_status,last_status from collector_sources where name='FGV'")).rows[0], activeBefore);
    const wrong = (await db.query<{ id: string }>("insert into source_candidates(url,domain) values('https://www.cebraspe.org.br/concursos/fixture','www.cebraspe.org.br') returning id")).rows[0].id;
    await db.query("update collector_sources set adapter='not-compiled' where name='Cebraspe'");
    const auditBefore = (await db.query<{ count: number }>("select count(*)::int count from ops_action_log")).rows[0].count;
    await assert.rejects(db.query("select ops_approve_source($1,$2,'Explicit but mismatched identity','https://www.cebraspe.org.br/concursos/fixture',true)", [actor, wrong]), /OPS_SOURCE_IDENTITY_MISMATCH/);
    assert.equal((await db.query<{ status: string }>("select status from source_candidates where id=$1", [wrong])).rows[0].status, "CANDIDATE", "mismatch rolls back candidate approval");
    assert.equal((await db.query<{ count: number }>("select count(*)::int count from ops_action_log")).rows[0].count, auditBefore);
    const linkedAudit = (await db.query<{ source_id: string; result: string }>("select details->>'source_id' source_id,details->>'result' result from ops_action_log where target_id=$1 order by created_at,id", [candidate])).rows;
    assert.ok(linkedAudit.every((row) => row.source_id === registered.id && row.result === "REGISTERED_DISABLED"));
    console.log("Sprint 2.6 PostgreSQL RBAC, complete source registration, explicit allowlisted activation, rollback, durable history and conflict review passed");
  } finally { await db.close(); }
}
main().catch((error) => { console.error(error); process.exitCode = 1; });
