import assert from "node:assert/strict";
import { resolveField } from "../src/lib/collector/fieldResolver";
import { extractIdentitySignals, scoreEntity, stableEntityKey } from "../src/lib/collector/entityResolution";
import { validateContestPage } from "../src/lib/collector/contestPageValidator";

const old = { value_json: 100, source_tier: 1, observed_at: "2026-01-01T00:00:00Z", source_url: "https://gov.br" };
assert.deepEqual(resolveField(100, 120, { tier: 2, observedAt: "2026-02-01T00:00:00Z" }, [old]).resolvedValue, 100);
assert.equal(resolveField(100, 120, { tier: 2, observedAt: "2026-02-01T00:00:00Z" }, [old]).conflict, true);
assert.equal(resolveField(100, 120, { tier: 1, observedAt: "2026-02-01T00:00:00Z", isAmendment: true }, [old]).resolvedValue, 120);
assert.equal(resolveField(100, 120, { tier: 1, observedAt: "2026-02-01T00:00:00Z" }, [old]).decision, "CONFLICT");
const official = { orgao: "Instituto Brasileiro do Meio Ambiente", banca: "Cebraspe", titulo: "IBAMA Edital 01/2026 Analista Ambiental" };
const dou = { orgao: "IBAMA", banca: null, titulo: "Instituto Brasileiro do Meio Ambiente publica Edital 01/2026 para Analista Ambiental" };
const officialIdentity = extractIdentitySignals({ title: official.titulo, orgao: official.orgao, banca: official.banca, cargos: ["Analista Ambiental"], url: "https://x/concursos/ibama2026" });
const douIdentity = extractIdentitySignals({ title: dou.titulo, orgao: dou.orgao, banca: dou.banca, cargos: ["Analista Ambiental"], url: "https://dou.gov.br/ibama" });
assert.ok(scoreEntity(officialIdentity, douIdentity).score >= 65);
assert.equal(stableEntityKey(officialIdentity), stableEntityKey(douIdentity));
assert.notEqual(scoreEntity(officialIdentity, extractIdentitySignals({ title: dou.titulo, orgao: "Outra Agencia", banca: dou.banca, url: "https://x/concursos/outra2026" })).decision, "AUTO_MATCH");
assert.equal(validateContestPage("FGV", "https://x/concursos", "Quem somos contatos avaliacoes").decision, "REJECT");
assert.equal(validateContestPage("Processo Seletivo Agencia Nacional XYZ 2027", "https://x/concursos/xyz", "Edital inscricoes vagas cargo cronograma").decision, "ACCEPT");
assert.equal(validateContestPage("AOCP", "https://x/concursos/status", "Concursos em andamento").decision, "REJECT");
console.log("1.3.1 validation passed");
