"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { Header, Footer } from "@/components/Header";

type Contest = { id: string; orgao: string; titulo: string; banca: string | null; vagas: number | null; salario: number | null; status: string; edital_url: string | null; prova_data: string | null; inscricao_fim: string | null; cargos: string[]; escolaridade: string[]; scope: string | null; state_code: string | null; city: string | null; hot_score: number | null };
type Meta = { page: number; perPage: number; total: number; totalPages: number };
const initial = { q: "", orgao: "", cargo: "", banca: "", cidade: "", estado: "", nivel: "", status: "", abrangencia: "", salarioMin: "", salarioMax: "", inscricao: "", sort: "RECENTES" };
const money = (value: number | null) => value == null ? "Salário não informado" : value.toLocaleString("pt-BR", { style: "currency", currency: "BRL" });

export default function ContestsPage() {
  const [form, setForm] = useState(initial); const [applied, setApplied] = useState(initial); const [page, setPage] = useState(1);
  const [items, setItems] = useState<Contest[]>([]); const [meta, setMeta] = useState<Meta>({ page: 1, perPage: 24, total: 0, totalPages: 0 }); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => {
    const controller = new AbortController();
    const params = new URLSearchParams({ page: String(page), perPage: "24", ...Object.fromEntries(Object.entries(applied).filter(([, value]) => value)) });
    fetch(`/api/concursos?${params}`, { cache: "no-store", signal: controller.signal }).then(async (response) => {
      const payload = await response.json(); if (!response.ok) setError("Não foi possível concluir a busca."); else { setError(""); setItems(payload.data); setMeta(payload.meta); } setLoading(false);
    }).catch((requestError) => { if (requestError instanceof Error && requestError.name !== "AbortError") { setError("Não foi possível concluir a busca."); setLoading(false); } });
    return () => controller.abort();
  }, [applied, page]);
  function submit(event: React.FormEvent) { event.preventDefault(); setLoading(true); setPage(1); setApplied(form); }
  function clear() { setLoading(true); setForm(initial); setPage(1); setApplied(initial); }
  const field = (key: keyof typeof initial) => ({ value: form[key], onChange: (event: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => setForm((current) => ({ ...current, [key]: event.target.value })) });
  return <div className="mesh min-h-screen"><Header /><main className="mx-auto max-w-6xl px-6 py-8"><h1 className="font-display text-3xl font-bold">Buscar concursos</h1><p className="mt-1 text-white/60">Busca nacional com filtros processados no servidor e resultados paginados.</p>
    <form onSubmit={submit} className="mt-6 rounded-3xl bg-white p-6 text-zinc-900"><div className="grid gap-3 md:grid-cols-4">
      <label className="text-sm md:col-span-2">Busca geral<input {...field("q")} placeholder="Órgão, título, banca ou cidade" className="mt-1 w-full rounded-xl border p-3" /></label><label className="text-sm">Órgão<input {...field("orgao")} className="mt-1 w-full rounded-xl border p-3" /></label><label className="text-sm">Cargo<input {...field("cargo")} className="mt-1 w-full rounded-xl border p-3" /></label>
      <label className="text-sm">Banca<input {...field("banca")} className="mt-1 w-full rounded-xl border p-3" /></label><label className="text-sm">Cidade<input {...field("cidade")} className="mt-1 w-full rounded-xl border p-3" /></label><label className="text-sm">UF<input {...field("estado")} maxLength={2} placeholder="SP" className="mt-1 w-full rounded-xl border p-3 uppercase" /></label><label className="text-sm">Nível<select {...field("nivel")} className="mt-1 w-full rounded-xl border p-3"><option value="">Todos</option><option value="FUNDAMENTAL">Fundamental</option><option value="MEDIO">Médio</option><option value="TECNICO">Técnico</option><option value="SUPERIOR">Superior</option></select></label>
      <label className="text-sm">Abrangência<select {...field("abrangencia")} className="mt-1 w-full rounded-xl border p-3"><option value="">Todas</option><option value="NACIONAL">Nacional</option><option value="FEDERAL">Federal</option><option value="ESTADUAL">Estadual</option><option value="MUNICIPAL">Municipal</option></select></label><label className="text-sm">Status<input {...field("status")} placeholder="INSCRICOES_ABERTAS" className="mt-1 w-full rounded-xl border p-3" /></label><label className="text-sm">Salário mínimo<input {...field("salarioMin")} type="number" min="0" className="mt-1 w-full rounded-xl border p-3" /></label><label className="text-sm">Salário máximo<input {...field("salarioMax")} type="number" min="0" className="mt-1 w-full rounded-xl border p-3" /></label>
      <label className="text-sm">Inscrição<select {...field("inscricao")} className="mt-1 w-full rounded-xl border p-3"><option value="">Qualquer período</option><option value="ABERTA">Aberta</option><option value="ENCERRANDO">Encerrando em 7 dias</option><option value="FUTURA">Futura</option></select></label><label className="text-sm">Ordenar<select {...field("sort")} className="mt-1 w-full rounded-xl border p-3"><option value="RECENTES">Mais recentes</option><option value="ENCERRANDO">Inscrições encerrando</option><option value="SALARIO">Maior salário</option><option value="VAGAS">Mais vagas</option><option value="HOT">Mais quentes</option></select></label>
    </div><div className="mt-5 flex gap-2"><button className="rounded-full bg-zinc-900 px-6 py-3 font-bold text-white">Buscar</button><button type="button" onClick={clear} className="rounded-full border px-6 py-3 font-bold">Limpar</button></div></form>
    <div className="mt-6 flex justify-between"><p className="text-sm text-white/60">{meta.total} concursos encontrados</p><p className="text-sm text-white/60">Página {meta.page} de {Math.max(1, meta.totalPages)}</p></div>{error && <p role="alert" className="mt-4 rounded-xl bg-red-500/15 p-3">{error}</p>}
    {loading ? <div className="mt-4 glass rounded-3xl p-8">Buscando…</div> : !items.length ? <div className="mt-4 rounded-3xl bg-white p-8 text-zinc-900">Nenhum concurso corresponde aos filtros.</div> : <div className="mt-4 grid gap-4 md:grid-cols-2">{items.map((contest) => <article key={contest.id} className="glass rounded-3xl p-5"><div className="flex justify-between gap-3"><div><p className="text-xs font-bold uppercase text-cyan-300">{contest.orgao}</p><h2 className="mt-1 text-lg font-bold"><Link href={`/concursos/${contest.id}`} className="hover:text-cyan-300">{contest.titulo}</Link></h2></div><span className="h-fit rounded-full bg-white/10 px-3 py-1 text-xs">{contest.status}</span></div><p className="mt-3 text-sm text-white/60">{contest.cargos?.join(", ") || "Cargo não informado"} · {contest.banca || "Banca não informada"}</p><p className="mt-1 text-sm text-white/60">{contest.city || contest.scope || "Local não informado"}{contest.state_code ? `/${contest.state_code}` : ""} · {contest.escolaridade?.join(", ") || "Nível não informado"}</p><div className="mt-4 flex flex-wrap gap-2 text-sm"><b>{money(contest.salario)}</b><span>·</span><span>{contest.vagas == null ? "Vagas não informadas" : `${contest.vagas} vagas`}</span><span>·</span><span>Prova {contest.prova_data || "não informada"}</span></div><div className="mt-4 flex flex-wrap gap-4"><Link href={`/concursos/${contest.id}`} className="text-sm font-bold text-cyan-300">Ver página completa →</Link>{contest.edital_url && <a href={contest.edital_url} target="_blank" rel="noopener noreferrer" className="text-sm font-bold text-cyan-300">Fonte oficial ↗</a>}</div></article>)}</div>}
    <div className="mt-6 flex justify-center gap-3"><button disabled={page <= 1 || loading} onClick={() => { setLoading(true); setPage((value) => value - 1); }} className="rounded-full border border-white/20 px-5 py-2 disabled:opacity-30">Anterior</button><button disabled={page >= meta.totalPages || loading} onClick={() => { setLoading(true); setPage((value) => value + 1); }} className="rounded-full border border-white/20 px-5 py-2 disabled:opacity-30">Próxima</button></div>
  </main><Footer /></div>;
}
