export type ConcursoDetailData = {
  id: string;
  titulo: string;
  orgao: string;
  banca: string | null;
  vagas: number | null;
  salario: number | null;
  inscricao_inicio: string | null;
  inscricao_fim: string | null;
  prova_data: string | null;
  cargos: unknown[];
  escolaridade: string[];
  status: string | null;
  scope: string | null;
  state_code: string | null;
  city: string | null;
  latitude: number | null;
  longitude: number | null;
  location_label: string | null;
  hot_score: number | null;
  hot_reasons: unknown[];
  quality_status: string;
  logical_key: string | null;
  edital_number: string | null;
  process_number: string | null;
  official_slug: string | null;
  official_source: string | null;
  cargo_key: string | null;
  cargo_group_key: string | null;
  edital_url: string | null;
  simulado_slug: string | null;
  requested_id: string;
  canonical_id: string;
  merged_into_id: string | null;
  is_merged: boolean;
  merged_from: string[];
  evidence: unknown[];
  identity_aliases: unknown[];
  documents: unknown[];
};
