"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import type { Session } from "@supabase/supabase-js";
import { Header, Footer } from "@/components/Header";
import { supabase } from "@/lib/supabase";

type Contest = { id: string; titulo: string; orgao: string; status: string; inscricao_fim: string | null; prova_data: string | null };
type Follow = { concurso_id: string; is_favorite: boolean; is_following: boolean };
type Notice = { event_id: string; read_at: string | null; created_at: string; notification_events: { event_type: string; title: string; message: string; source_url: string | null; concursos: { titulo: string; orgao: string } | null } };
const labels: Record<string, string> = { NOVO_EDITAL: "Novo edital", RETIFICACAO: "Retificação", INSCRICAO_ABERTA: "Inscrição aberta", INSCRICAO_ENCERRANDO: "Inscrição encerrando", PROVA_MARCADA: "Prova marcada", MUDANCA_RELEVANTE: "Mudança relevante" };

export default function FollowPage() {
  const [session, setSession] = useState<Session | null>(null); const [contests, setContests] = useState<Contest[]>([]); const [follows, setFollows] = useState<Follow[]>([]); const [notices, setNotices] = useState<Notice[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  async function load(active: Session) {
    setLoading(true); setError(""); const headers = { authorization: `Bearer ${active.access_token}` };
    const [followResponse, noticeResponse] = await Promise.all([fetch("/api/follows", { headers, cache: "no-store" }), fetch("/api/notifications", { headers, cache: "no-store" })]);
    if (!followResponse.ok || !noticeResponse.ok) setError("Não foi possível carregar seu acompanhamento agora.");
    else { const followPayload = await followResponse.json(); const noticePayload = await noticeResponse.json(); setContests(followPayload.data.contests); setFollows(followPayload.data.follows); setNotices(noticePayload.data); }
    setLoading(false);
  }
  useEffect(() => { supabase.auth.getSession().then(({ data }) => { setSession(data.session); if (data.session) void load(data.session); else setLoading(false); }); const { data } = supabase.auth.onAuthStateChange((_event, active) => { setSession(active); if (active) void load(active); else setLoading(false); }); return () => data.subscription.unsubscribe(); }, []);
  function state(id: string) { return follows.find((item) => item.concurso_id === id) || { concurso_id: id, is_favorite: false, is_following: false }; }
  async function save(contestId: string, favorite: boolean, following: boolean) { if (!session) return; const response = await fetch("/api/follows", { method: "POST", headers: { "content-type": "application/json", authorization: `Bearer ${session.access_token}` }, body: JSON.stringify({ concursoId: contestId, favorite, following }) }); if (!response.ok) return setError("Não foi possível salvar sua escolha."); setFollows((items) => !favorite && !following ? items.filter((item) => item.concurso_id !== contestId) : [...items.filter((item) => item.concurso_id !== contestId), { concurso_id: contestId, is_favorite: favorite, is_following: following }]); }
  async function read(eventId: string) { if (!session) return; const response = await fetch("/api/notifications", { method: "PATCH", headers: { "content-type": "application/json", authorization: `Bearer ${session.access_token}` }, body: JSON.stringify({ eventId }) }); if (response.ok) setNotices((items) => items.map((item) => item.event_id === eventId ? { ...item, read_at: new Date().toISOString() } : item)); }
  return <div className="mesh min-h-screen"><Header /><main className="mx-auto max-w-6xl px-6 py-8"><h1 className="font-display text-3xl font-bold">Favoritos e alertas</h1><p className="mt-1 text-white/60">Acompanhe concursos sem e-mail ou notificações repetitivas.</p>
    {loading ? <div className="mt-6 glass rounded-3xl p-8">Carregando acompanhamento…</div> : !session ? <div className="mt-6 rounded-3xl bg-white p-8 text-zinc-900"><h2 className="text-2xl font-bold">Entre para acompanhar concursos</h2><Link href="/conta" className="mt-5 inline-block rounded-full bg-zinc-900 px-6 py-3 font-bold text-white">Entrar ou criar conta</Link></div> : <div className="mt-6 grid gap-6 lg:grid-cols-2">
      <section className="rounded-3xl bg-white p-6 text-zinc-900"><h2 className="text-xl font-bold">Concursos</h2><p className="text-sm text-zinc-500">Favoritar organiza sua lista; seguir também recebe eventos novos nesta central.</p><div className="mt-4 max-h-[620px] space-y-3 overflow-auto">{contests.map((contest) => { const current = state(contest.id); return <article key={contest.id} className="rounded-2xl border border-zinc-200 p-4"><b>{contest.orgao} · {contest.titulo}</b><p className="mt-1 text-xs text-zinc-500">{contest.status} · prova {contest.prova_data || "não informada"}</p><div className="mt-3 flex gap-2"><button onClick={() => void save(contest.id, !current.is_favorite, current.is_following)} className={`rounded-full px-4 py-2 text-sm font-bold ${current.is_favorite ? "bg-amber-400" : "border"}`}>{current.is_favorite ? "★ Favorito" : "☆ Favoritar"}</button><button onClick={() => void save(contest.id, current.is_favorite, !current.is_following)} className={`rounded-full px-4 py-2 text-sm font-bold ${current.is_following ? "bg-violet-700 text-white" : "border"}`}>{current.is_following ? "Seguindo" : "Seguir"}</button></div></article>; })}</div></section>
      <section className="glass rounded-3xl p-6"><div className="flex justify-between"><h2 className="text-xl font-bold">Notificações</h2><span className="text-sm text-white/50">{notices.filter((item) => !item.read_at).length} não lidas</span></div>{!notices.length ? <p className="mt-4 rounded-2xl bg-white/5 p-5 text-sm text-white/60">Siga um concurso. Novos editais, retificações, prazos, provas e mudanças relevantes aparecerão aqui.</p> : <div className="mt-4 space-y-3">{notices.map((notice) => <article key={notice.event_id} className={`rounded-2xl p-4 ${notice.read_at ? "bg-white/5" : "bg-cyan-400/10 ring-1 ring-cyan-300/30"}`}><span className="text-xs font-bold uppercase text-cyan-300">{labels[notice.notification_events.event_type] || notice.notification_events.event_type}</span><h3 className="mt-1 font-bold">{notice.notification_events.title}</h3><p className="mt-1 text-sm text-white/60">{notice.notification_events.message}</p>{!notice.read_at && <button onClick={() => void read(notice.event_id)} className="mt-3 text-xs font-bold text-cyan-300">Marcar como lida</button>}</article>)}</div>}</section>
    </div>}{error && <p role="alert" className="mt-4 rounded-xl bg-red-500/15 p-3 text-red-100">{error}</p>}</main><Footer /></div>;
}
